import { ConnectButton } from '@rainbow-me/rainbowkit'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>BiggieBank</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <h1 className="text-3xl font-bold">
          BiggieBank
        </h1>
        <main className={styles.main}>
          <ConnectButton />
        </main>
      </div>
    </>
  )
}
